apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring-boot-crud.fullname" . }}
  labels:
    {{- include "spring-boot-crud.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "spring-boot-crud.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      nodePort: {{ .Values.service.nodePort }}
