replicaCount: 2

config:
  springProfilesActive: default
  serverPort: "8080"
  h2ConsoleEnabled: "true"

secret:
  datasourceUsername: sa
  datasourcePassword: ""

image:
  repository: spring-boot-crud
  tag: latest
  pullPolicy: Never

service:
  type: NodePort
  port: 8080
  targetPort: 8080
  nodePort: 30080

resources: {}
